PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX bridg: <http://www.bridgmodel.org/owl#>
PREFIX core: <http://www.w3.org/2013/12/FDA-TA/core#>
PREFIX xplant: <http://www.w3.org/2013/12/FDA-TA/transplant#>
PREFIX renal: <http://www.w3.org/2013/12/FDA-TA/renal#>
PREFIX data: <http://www.w3.org/2013/12/FDA-TA/datatypes#>

SELECT * {
      <http://www.w3.org/2013/12/FDA-TA/tests/RenalTransplantation/subject-sue#asSubject>
        bridg:Subject.performingBiologicEntity [ foaf:name ?name ] ;
        core:hasOutcomeAssessment ?oa .
          ?oa a renal:RenalFunctionOutcomeAssessment .
          { SELECT ?oa { ?oa core:hasObservation [ a renal:GfrFlowRateObservation] } GROUP BY ?oa }
#          MINUS {
#            ?oa core:hasObservation
#                    [ a renal:GfrFlowRateObservation ; core:hasObservationTime ?date1 ; core:hasResultValue [ data:value ?gfr1 ] ] ,
#                    [ a renal:GfrFlowRateObservation ; core:hasObservationTime ?date2 ; core:hasResultValue [ data:value ?gfr2 ] ]
#            FILTER (?date1 < ?date2 && ?gfr1 < ?gfr2)
#          }
}